version: "3.9"

services:
  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: dockerfile.dev
    depends_on:
      - db
    volumes:
      - "./backend:/backend"
    env_file:
      - ./backend/.dev.env
    ports:
      - "8000:8000"
    networks:
      - chat-network
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    networks:
      - chat-network
    command: serve -s -p 3000

  db:
    image: mariadb
    container_name: mariadb
    networks:
      - chat-network
    environment:
      MYSQL_ROOT_PASSWORD: 123456789

  nginx:
    build: ./nginx
    container_name: nginx
    ports: 
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - chat-network
    depends_on:
      - db
      - frontend
      - backend

networks:
  chat-network:
    driver: bridge
