version: "3.9"

services:
  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: dockerfile.dev
    depends_on:
      - db
    volumes:
      - "./backend:/app"
    env_file:
      - backend/.dev.env
    ports:
      - "8000:8000"
    networks:
      - chat-network
    command: python /app/manage.py runserver 0.0.0.0:8000

  frontend:
    container_name: frontend
    build: ./frontend
    depends_on:
      - backend
    build: 
      context: ./frontend
      dockerfile: dockerfile.dev
    volumes:
      - "./frontend:/app"
    ports:
      - "3000:3000"
    networks:
      - chat-network
    command: npm run dev

  db:
    image: mariadb
    container_name: mariadb
    networks:
      - chat-network
    environment:
      MYSQL_ROOT_PASSWORD: 123456789

networks:
  chat-network:
    driver: bridge
